In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sklearn
import random

In [2]:
from vaccination_functions import *
from acs_data_functions import *
from tea_data_functions import *

In [3]:
tx_mmr_vac_rates = pd.read_csv("../TX_MMR_vax_rate_24_25.csv")
tx_mmr_vac_rates.head()

,Facility Number,School Type,School District or Name,Facility Address,County,MMR Vaccination Rate,Age Group
0,9057829000,Public School,A+ ACADEMY,"8225 BRUTON RD, DALLAS, TX, .",Dallas,96.77,Kindergarten
1,9109901000,Public School,ABBOTT ISD,"P O BOX 226, ABBOTT, TX, .",Hill,95.24,Kindergarten
2,9095901000,Public School,ABERNATHY ISD,"505 7TH ST, ABERNATHY, TX, .",Hale,93.22,Kindergarten
3,9221901000,Public School,ABILENE ISD,"P O BOX 981, ABILENE, TX, .",Taylor,97.76,Kindergarten
4,9014901000,Public School,ACADEMY ISD,"704 E MAIN ST, LITTLE RIVER, TX, .",Bell,98.04,Kindergarten

In [56]:
tea_data_path = "../TEA_data/"
grade_enrollment = pd.read_csv(tea_data_path+"Enrollment_Report_Statewide_Campuses_Grade_2024_2025.csv")
gender_enrollment = pd.read_csv(tea_data_path+"Enrollment_Report_Statewide_Campuses_Gender_2024_2025_clean_duplicates.csv")
ethnicity_enrollment = pd.read_csv(tea_data_path+"Enrollment_Report_Statewide_Campuses_Ethnicity_2024_2025_clean_duplicates.csv")

In [23]:
grade_enrollment.head()

,YEAR,REGION,COUNTY NAME,DISTRICT,DISTRICT NAME,CAMPUS,CAMPUS NAME,GRADE GROUP NAME,GRADE,ENROLLMENT
0,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Pre-kindergarten,147
1,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Kindergarten,94
2,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Grade 1,117
3,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Grade 2,92
4,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Grade 3,98

In [12]:
gender_enrollment.columns

Index(['YEAR', 'REGION', 'COUNTY NAME', 'DISTRICT', 'DISTRICT NAME', 'CAMPUS',
       'CAMPUS NAME', 'GRADE GROUP NAME', 'GENDER', 'ENROLLMENT'],
      dtype='str')

In [13]:
gender_enrollment.head()

,YEAR,REGION,COUNTY NAME,DISTRICT,DISTRICT NAME,CAMPUS,CAMPUS NAME,GRADE GROUP NAME,GENDER,ENROLLMENT
0,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Female,448
1,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Male,440
2,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829002.0,A+ SECONDARY SCHOOL,HIGH SCHOOL,Female,363
3,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829002.0,A+ SECONDARY SCHOOL,HIGH SCHOOL,Male,427
4,2024-2025,4.0,HARRIS COUNTY,101871.0,A+ UNLIMITED POTENTIAL,101871102.0,A+ UNLIMITED POTENTIAL - UNIVERSITY,MIDDLE SCHOOL,Female,74

In [24]:
ethnicity_enrollment.head()

,YEAR,REGION,COUNTY NAME,DISTRICT,DISTRICT NAME,CAMPUS,CAMPUS NAME,GRADE GROUP NAME,ETHNICITY,ENROLLMENT
0,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Asian,<10
1,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Black or African American,33
2,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Hispanic/Latino,836
3,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Two or more races,<10
4,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,White,14

In [42]:
common_campus_column_drop = ['REGION', 'YEAR', 'DISTRICT', 'CAMPUS']
campus_index_col = ['COUNTY NAME', 'DISTRICT NAME', 'CAMPUS NAME', 'GRADE GROUP NAME']

In [43]:
grade_enrollment_clean, grade_enrollment_pivot = pivot_enrollment_dataset(grade_enrollment, 'GRADE', drop_columns=common_campus_column_drop, index_columns=campus_index_col)
grade_enrollment_pivot.head()

GRADE,County_Name,District_Name,CAMPUS NAME,GRADE GROUP NAME,Early Education,Grade 1,Grade 10,Grade 11,Grade 12,Grade 2,Grade 3,Grade 4,Grade 5,Grade 6,Grade 7,Grade 8,Grade 9,Kindergarten,Pre-kindergarten
0,ANDERSON COUNTY,CAYUGA ISD,CAYUGA EL,ELEMENTARY,<10,50,0,0,0,40,43,42,40,0,0,0,0,41,<10
1,ANDERSON COUNTY,CAYUGA ISD,CAYUGA H S,HIGH SCHOOL,0,0,53,51,37,0,0,0,0,0,0,0,49,0,0
2,ANDERSON COUNTY,CAYUGA ISD,CAYUGA MIDDLE,MIDDLE SCHOOL,0,0,0,0,0,0,0,0,0,41,38,45,0,0,0
3,ANDERSON COUNTY,ELKHART ISD,ELKHART EL,ELEMENTARY,<10,92,0,0,0,81,0,0,0,0,0,0,0,98,<90
4,ANDERSON COUNTY,ELKHART ISD,ELKHART H S,HIGH SCHOOL,0,0,87,75,65,0,0,0,0,0,0,0,78,0,0

In [54]:
ethnicity_enrollment[ethnicity_enrollment.duplicated(['COUNTY NAME', 'DISTRICT NAME', 'CAMPUS NAME', 'GRADE GROUP NAME', 'ETHNICITY'], keep=False)]

Empty DataFrame
Columns: [YEAR, REGION, COUNTY NAME, DISTRICT, DISTRICT NAME, CAMPUS, CAMPUS NAME, GRADE GROUP NAME, ETHNICITY, ENROLLMENT]
Index: []

In [55]:
ethnicity_enrollment_clean, ethnicity_enrollment_pivot = pivot_enrollment_dataset(ethnicity_enrollment, 'ETHNICITY', drop_columns=common_campus_column_drop, index_columns=campus_index_col)

In [57]:
gender_enrollment[gender_enrollment.duplicated(['COUNTY NAME', 'DISTRICT NAME', 'CAMPUS NAME', 'GRADE GROUP NAME', 'GENDER'], keep=False)]

Empty DataFrame
Columns: [YEAR, REGION, COUNTY NAME, DISTRICT, DISTRICT NAME, CAMPUS, CAMPUS NAME, GRADE GROUP NAME, GENDER, ENROLLMENT]
Index: []

In [ ]:
gender_enrollment_clean, gender_enrollment_pivot = pivot_enrollment_dataset(gender_enrollment, 'GENDER', drop_columns=common_campus_column_drop, index_columns=campus_index_col)

In [ ]:
ethnicity_enrollment.head()

,YEAR,REGION,COUNTY NAME,DISTRICT,DISTRICT NAME,CAMPUS,CAMPUS NAME,GRADE GROUP NAME,ETHNICITY,ENROLLMENT
0,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Asian,<10
1,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Black or African American,33
2,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Hispanic/Latino,836
3,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,Two or more races,<10
4,2024-2025,10.0,DALLAS COUNTY,57829.0,A+ ACADEMY,57829001.0,A+ ACADEMY EL,ELEMENTARY,White,14

In [ ]:
#unknown_values = list(range(10, 1980, 10))
#rand_gen_dict = {}
#for i in unknown_values:
#    rand_gen = random.randint(1, i-1)
#    rand_gen_dict[f'{i}'] = rand_gen

In [ ]:
#rand_gen10 = random.randint(1, 9)
#rand_gen20 = random.randint(1, 19)
#rand_gen30 = random.randint(1, 29)
#rand_gen40 = random.randint(1, 49)

In [ ]:
#unknown_rand_dict = {'<10': rand_gen_dict['10'], '<20': rand_gen20, '<30': rand_gen30, '<40': rand_gen40,}

In [ ]:
#ethnicity_enrollment['ENROLLMENT'].replace(unknown_rand_dict)

0          2
1         33
2        836
3          2
4         14
        ...
48840      2
48841     22
48842      2
48843     13
48844    182
Name: ENROLLMENT, Length: 48845, dtype: object

In [ ]:
#ethnicity_enrollment[ethnicity_enrollment['ENROLLMENT'].str.contains('<')]
ethnicity_enrollment['ENROLLMENT'][ethnicity_enrollment['ENROLLMENT'].str.contains('<')].unique()

<StringArray>
[   '<10',    '<70',    '<20',    '<30',    '<90',    '<60',   '<330',
    '<50',    '<40',   '<180',   '<240',   '<170',   '<280',    '<80',
   '<340',   '<130',   '<100',   '<120',   '<160',   '<520',   '<390',
   '<880',   '<870',   '<420',   '<290',   '<510',   '<350',   '<230',
   '<110',   '<150',   '<270',   '<200',   '<140',   '<250',   '<190',
   '<650',   '<560', '<1,980',   '<450',   '<300',   '<570',   '<460',
   '<690',   '<310',   '<400',   '<440',   '<320', '<1,310', '<1,300',
   '<640',   '<220',   '<260',   '<680',   '<370',   '<720',   '<210',
   '<360',   '<530',   '<610', '<1,960',   '<540',   '<480', '<1,120',
 '<1,380',   '<600',   '<580',   '<430', '<1,970',   '<670',   '<500',
   '<410',   '<730',   '<740',   '<380',   '<550',   '<490',   '<630',
   '<620',   '<660',   '<760',   '<790',   '<770',   '<820',   '<590']
Length: 84, dtype: str

In [ ]:
grade_enrollment['ENROLLMENT'][grade_enrollment['ENROLLMENT'].str.contains('<')].unique()

<StringArray>
[   '<10',    '<20',    '<30',   '<110',    '<80',    '<70',    '<60',
    '<40',    '<50',   '<100',    '<90',   '<390',   '<150',   '<120',
 '<1,780', '<1,690',   '<170',   '<190',   '<200',   '<350',   '<530',
   '<210',   '<140',   '<330',   '<320',   '<480',   '<340',   '<410',
   '<130',   '<620',   '<610',   '<570',   '<520',   '<270',   '<310',
   '<220',   '<540',   '<180',   '<240',   '<260',   '<250',   '<230',
   '<280',   '<290',   '<380',   '<820',   '<760',   '<160',   '<600',
   '<590',   '<680',   '<630',   '<640',   '<780',   '<370', '<1,110',
 '<1,010',   '<420',   '<440',   '<460', '<1,130', '<1,180',   '<450',
   '<500',   '<470',   '<560',   '<430',   '<300',   '<360',   '<490',
   '<550',   '<510',   '<830',   '<870',   '<660',   '<400',   '<670',
   '<580',   '<740',   '<690',   '<710',   '<650',   '<790',   '<930',
   '<890',   '<800']
Length: 86, dtype: str

In [ ]:
gender_enrollment['ENROLLMENT'][gender_enrollment['ENROLLMENT'].str.contains('<')].unique()

<StringArray>
[ '<10',  '<20',  '<30',  '<40',  '<80', '<100', '<230', '<200', '<190',
  '<60', '<250', '<260', '<290',  '<70',  '<50', '<140', '<160', '<130',
 '<150', '<210', '<120', '<170',  '<90', '<110', '<560', '<760', '<180',
 '<220', '<500', '<300', '<330', '<320', '<240', '<430', '<380', '<280',
 '<270', '<540', '<360']
Length: 39, dtype: str